[build]
  command = "npm run build"
  publish = "dist"

# Zwingt Netlify dazu, den Service Worker niemals zwischenzuspeichern (Wichtig für iOS-Updates)
[[headers]]
  for = "/sw.js"
  [headers.values]
    cache-control = "no-cache, no-store, must-revalidate"
    expires = "0"

# Zwingt Netlify dazu, das Manifest niemals zwischenzuspeichern
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    cache-control = "no-cache, no-store, must-revalidate"
    expires = "0"
